FROM node:18-alpine

RUN addgroup app && adduser -S -G app app

USER app

WORKDIR /usr/app

COPY package*.json ./

USER root

RUN chown -R app:app .

USER app

RUN npm install

COPY . .

EXPOSE 5173

CMD npm run dev